

services:
  db:
    image: postgres:15
    container_name: goodstewards_db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=goodstewards
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d goodstewards"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build: ./backend
    container_name: goodstewards_backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    environment:
      - ENVIRONMENT=development
      - DATABASE_URL=postgresql+psycopg_async://postgres:postgres@db:5432/goodstewards
      - SECRET_KEY=your-super-secret-key-change-this-in-production
      - BAML_CLIENT_MODE=http
      - BAML_CLIENT_URL=http://localhost:2022
    depends_on:
      db:
        condition: service_healthy

volumes:
  postgres_data:
    driver: local