# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

import typing
import typing_extensions
from pydantic import BaseModel, ConfigDict

import baml_py

from . import types

StreamStateValueT = typing.TypeVar('StreamStateValueT')
class StreamState(BaseModel, typing.Generic[StreamStateValueT]):
    value: StreamStateValueT
    state: typing_extensions.Literal["Pending", "Incomplete", "Complete"]
# #########################################################################
# Generated classes (2)
# #########################################################################

class ReceiptData(BaseModel):
    vendor_name: typing.Optional[str] = None
    purchase_date: typing.Optional[str] = None
    county: typing.Optional[str] = None
    subtotal_amount: typing.Optional[float] = None
    tax_amount: typing.Optional[float] = None
    total_amount: typing.Optional[float] = None
    expense_category: typing.Optional[str] = None
    is_donation: typing.Optional[bool] = None
    tax_breakdowns: typing.List["TaxBreakdown"]

class TaxBreakdown(BaseModel):
    tax_type: typing.Optional[types.TaxType] = None
    tax_rate: typing.Optional[float] = None
    amount: typing.Optional[float] = None

# #########################################################################
# Generated type aliases (0)
# #########################################################################
