"""Add missing user columns

Revision ID: 69da2f6dedf1
Revises: f8c03a1f8cd7
Create Date: 2025-07-23 16:02:47.481494

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '69da2f6dedf1'
down_revision: Union[str, Sequence[str], None] = 'f8c03a1f8cd7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('contact_telephone', sa.String(), nullable=True))
    op.add_column('user', sa.Column('is_special_user', sa.Boolean(), nullable=False))
    op.add_column('user', sa.Column('special_user_type', sa.Enum('anonymous_donor', 'unknown_user', 'one_time_donor', name='specialusertype'), nullable=True))
    op.alter_column('user', 'email',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('user', 'hashed_password',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'hashed_password',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('user', 'email',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('user', 'special_user_type')
    op.drop_column('user', 'is_special_user')
    op.drop_column('user', 'contact_telephone')
    # ### end Alembic commands ###
